spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://root:root@localhost:27017/ticketBookingDb?authSource=admin}
      database: ticketBookingDb
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
