services:
  mongodb:
    container_name: "assignment-2-spring-mongo"
    image: mongo:6.0
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb_data_container:/data/db

  redis:
    container_name: "assignment-2-spring-redis"
    image: redis/redis-stack
    ports:
      - "127.0.0.1:6379:6379"
      - "127.0.0.1:8001:8001"
    volumes:
      - redis_data_container:/data

volumes:
  mongodb_data_container:
  redis_data_container:
